# permissions for end users to view harvestermachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: harvestermachine-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-harvester
    app.kubernetes.io/part-of: cluster-api-provider-harvester
    app.kubernetes.io/managed-by: kustomize
  name: harvestermachine-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - harvestermachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - harvestermachines/status
  verbs:
  - get
