apiVersion: v1
kind: Namespace
metadata:
  name: ${CLUSTER_NAMESPACE}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster 
metadata:
  namespace: ${CLUSTER_NAMESPACE}
  name: ${CLUSTER_NAME} 
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.42.0.0/16
    services:
      cidrBlocks:
      - 10.43.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: ${CLUSTER_NAME}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: HarvesterCluster
    name: ${CLUSTER_NAME}-hv
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: HarvesterCluster
metadata:
  name: ${CLUSTER_NAME}-hv
  namespace: ${CLUSTER_NAMESPACE}
spec:
  loadBalancerConfig:
    ipamType: dhcp
  server: 
  identitySecret: 
    namespace: ${CLUSTER_NAMESPACE}
    name: ${CLUSTER_NAME}-identity-secret
---
apiVersion: v1
kind: Secret
metadata:
  namespace: ${CLUSTER_NAMESPACE}
  name: ${CLUSTER_NAME}-identity-secret
data: 
  kubeconfig: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKbGFrTkRRVklyWjBGM1NVSkJaMGxDUVVSQlMwSm5aM0ZvYTJwUFVGRlJSRUZxUVd0TlUwbDNTVUZaUkZaUlVVUkVRbXg1WVRKVmVVeFlUbXdLWTI1YWJHTnBNV3BaVlVGNFRtcGpNRTFFVVhoTmVsa3pUVUkwV0VSVVNYcE5SRVY0VDBSRmVFMXFhM2xPTVc5WVJGUk5lazFFUlhoT1ZFVjRUV3ByZVFwT01XOTNTa1JGYVUxRFFVZEJNVlZGUVhkM1dtTnRkR3hOYVRGNldsaEtNbHBZU1hSWk1rWkJUVlJaTTA1RVFUQk5WRTB5VG5wQ1drMUNUVWRDZVhGSENsTk5ORGxCWjBWSFEwTnhSMU5OTkRsQmQwVklRVEJKUVVKTlVWUlJSM0pEZDB4clIwUjJUMWg1VDFaamJtaFpSMHN6V0d4TlNUUkVOVGREU21OWWRuUUtjMDU2Tm1OSFZsTTBTbVYxV1RNeldrMDNkM0pUUjNkT01tcHhaMmh6ZW5sa1puUm5Ua0pxWjJkUU5HRmFTMWRxVVdwQ1FVMUJORWRCTVZWa1JIZEZRZ292ZDFGRlFYZEpRM0JFUVZCQ1owNVdTRkpOUWtGbU9FVkNWRUZFUVZGSUwwMUNNRWRCTVZWa1JHZFJWMEpDVkhWWE0wSkpkR1E0T0hVMk0zQlNiRU5TQ25sbFJXRlZZbTV5WlZSQlMwSm5aM0ZvYTJwUFVGRlJSRUZuVGtwQlJFSkhRV2xGUVhJeE0xQmthVlJ2Y0habVYyRjRjVEJpVW10ME1TdEhWVEl2VkVNS1ZsRkpWbXczT1dkWlIwMVdNV00wUTBsUlEzQXpiRFl2UkhWNlN5dFNkVWM1TVhKek5EVnpSMWh5TXpGS1Mwa3dTbE56YjBvNFZrVklNRU5RUTJjOVBRb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENnPT0KICAgIHNlcnZlcjogaHR0cHM6Ly8xOTIuMTY4LjEuMTYxOjY0NDMKICBuYW1lOiBkZWZhdWx0CmNvbnRleHRzOgotIGNvbnRleHQ6CiAgICBjbHVzdGVyOiBkZWZhdWx0CiAgICB1c2VyOiBkZWZhdWx0CiAgbmFtZTogZGVmYXVsdApjdXJyZW50LWNvbnRleHQ6IGRlZmF1bHQKa2luZDogQ29uZmlnCnByZWZlcmVuY2VzOiB7fQp1c2VyczoKLSBuYW1lOiBkZWZhdWx0CiAgdXNlcjoKICAgIGNsaWVudC1jZXJ0aWZpY2F0ZS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKclZFTkRRVlJwWjBGM1NVSkJaMGxKU21oMWNEbDVha2RuU21OM1EyZFpTVXR2V2tsNmFqQkZRWGRKZDBwRVJXbE5RMEZIUVRGVlJVRjNkMW9LWTIxMGJFMXBNV3BpUjJ4c1ltNVJkRmt5UmtGTlZGa3pUa1JCTUUxVVRUSk9la0ZsUm5jd2VVMTZRWGhOVkdkNFRWUkpOVTFxWkdGR2R6QjVUa1JCZUFwTlZHZDRUVlJKTlUxcVpHRk5SRUY0Um5wQlZrSm5UbFpDUVc5VVJHNU9OV016VW14aVZIQjBXVmhPTUZwWVNucE5VbFYzUlhkWlJGWlJVVVJGZDNoNkNtVllUakJhVnpBMldWZFNkR0ZYTkhkWFZFRlVRbWRqY1docmFrOVFVVWxDUW1kbmNXaHJhazlRVVUxQ1FuZE9RMEZCVkZrNVNHTlNTRzR3V2tjdmVVUUtSRlZOTVZaT09IUXhVVlpoUTAxRWRFVnROVWxXUVRGNGNtazRlR3BIV2pad01reHBkVlJIWjJaS1UxQlBMME5xUVcxT1NFNTVjVmRISzJ4SFdGZFliUXBoZVRoU2IzcG1RVzh3WjNkU2FrRlBRbWRPVmtoUk9FSkJaamhGUWtGTlEwSmhRWGRGZDFsRVZsSXdiRUpCZDNkRFoxbEpTM2RaUWtKUlZVaEJkMGwzQ2toM1dVUldVakJxUWtKbmQwWnZRVlYyWlVrMmMyWkdjMEpTZVdvemVUTnlXVlpIU0cxUVRrVXdVMk4zUTJkWlNVdHZXa2w2YWpCRlFYZEpSRkozUVhjS1VrRkpaMlpYUlVOQldsWmhSRGRGUWtwaFVqbFhUV1ZQVmpKeFFYZFBUMHgzY2k4d1ZWcEtOSFpqTTA0clduTkRTVVZLVkhnMFdEWnNhbFJWYzNGNmN3cHZRVTU1TTFSUWMyRXlaMU53VDNWSGIyWjBhR051Y0RoT05UQjBDaTB0TFMwdFJVNUVJRU5GVWxSSlJrbERRVlJGTFMwdExTMEtMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VKbGFrTkRRVklyWjBGM1NVSkJaMGxDUVVSQlMwSm5aM0ZvYTJwUFVGRlJSRUZxUVd0TlUwbDNTVUZaUkZaUlVVUkVRbXg1WVRKVmVVeFhUbk1LWVZkV2RXUkRNV3BaVlVGNFRtcGpNRTFFVVhoTmVsa3pUVUkwV0VSVVNYcE5SRVY0VDBSRmVFMXFhM2xPTVc5WVJGUk5lazFFUlhoT1ZFVjRUV3ByZVFwT01XOTNTa1JGYVUxRFFVZEJNVlZGUVhkM1dtTnRkR3hOYVRGcVlrZHNiR0p1VVhSWk1rWkJUVlJaTTA1RVFUQk5WRTB5VG5wQ1drMUNUVWRDZVhGSENsTk5ORGxCWjBWSFEwTnhSMU5OTkRsQmQwVklRVEJKUVVKTVdtWldRV0ZwUTNGdmRVVmpZVVp2WTJ4UFNHNXVUM0JzTUhoYVMyVnlVMUZ1VTJNM1ZHTUthRmR6TDBGTFluazRLekYxWTBkcldIZ3dSMWRWTVRCUFNISmlUbmxJTUVSNlJscGhiR0ZVWVUxSmVVSnplbmxxVVdwQ1FVMUJORWRCTVZWa1JIZEZRZ292ZDFGRlFYZEpRM0JFUVZCQ1owNVdTRkpOUWtGbU9FVkNWRUZFUVZGSUwwMUNNRWRCTVZWa1JHZFJWMEpDVXprMGFuRjRPRmQzUmtoTFVHWk1aWFJvQ2xWWlpWazRNRlJTU25wQlMwSm5aM0ZvYTJwUFVGRlJSRUZuVGtwQlJFSkhRV2xGUVhoTlVHMU9MMk5WYkVrdmRXSTJPV05xTVd0RGMzcHhZbFJzZGxNS1NXbEhlSFpLUkd4SFJuVTRRMFJGUTBsUlJHMHllVEE1ZEZJNFJsQkdVV3h0UW5KeFFWSkVXRXRGVDFGMGMzRk5PWGhUYUVWcE1qWkdlblJCYkZFOVBRb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENnPT0KICAgIGNsaWVudC1rZXktZGF0YTogTFMwdExTMUNSVWRKVGlCRlF5QlFVa2xXUVZSRklFdEZXUzB0TFMwdENrMUlZME5CVVVWRlNVdGtSak5XVjJkdFNVeERlRlJ6U0VwU2NYWXpSbmRuWXl0U05rTlRNSHBxT0dOaWNIaE9NSHBVT0RKdlFXOUhRME54UjFOTk5Ea0tRWGRGU0c5VlVVUlJaMEZGTWxCU00wVlNOVGxIVW5ZNFozY3hSRTVXVkdaTVpGVkdWMmRxUVRkU1NuVlRSbEZPWTJFMGRrMVplRzFsY1dScE5ISnJlQXB2U0hsVmFucDJkMjkzU21wU2VtTnhiR2gyY0ZKc01XdzFiWE4yUldGTk0zZEJQVDBLTFMwdExTMUZUa1FnUlVNZ1VGSkpWa0ZVUlNCTFJWa3RMUzB0TFFvPQo=
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  namespace: ${CLUSTER_NAMESPACE}
  name: ${CLUSTER_NAME}-control-plane
spec:
  replicas: ${CONTROLPLANE_REPLICAS}
  kubeadmConfigSpec: 
    initConfiguration: {}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: HarvesterMachineTemplate
      name: ${CLUSTER_NAME}-cp-machine
      namespace: ${CLUSTER_NAMESPACE}
  version: v1.26.6 
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: HarvesterMachineTemplate
metadata:
  namespace: ${CLUSTER_NAMESPACE}
  name: ${CLUSTER_NAME}-cp-machine
spec:
  template: 
    spec:
      targetNamespace: default
      cpu: 2
      memory: 8Gi
      sshUser: ubuntu
      sshKeyPair: ${SSH_KEYPAIR}  
      networks:
      - untagged
      volumes:
      - volumeType: image 
        imageName: ${VM_IMAGE_NAME}
        volumeSize: 50Gi
        bootOrder: 0
