name: pr_size_labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '50'
          s_max_size: '200'
          m_max_size: '100'
          l_max_size: '2000'
          fail_if_xl: 'false'
          message_if_xl: >
            This PR exceeds the recommended max size of 2000 lines.
            Please make sure you are NOT addressing multiple issues with one PR 
            and split it up if possible 😊
